main: tld.example.myplugin.Main
name: ServerEssentials
version: 0.0.5
author: KingCloudNinja
description: Server Essentials Plugin
commands:
  hype:
    description: Server Essentials Command
    usage: 
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  spec:
    description: Server Essentials Command
    usage: 
    permission: server.mod
    permission-message: Unknown command. Type "/help" for help.
  v:
    description: Server Essentials Command
    usage: 
    permission: server.mod
    permission-message: Unknown command. Type "/help" for help.
  unv:
    description: Server Essentials Command
    usage: 
    permission: server.mod
    permission-message: Unknown command. Type "/help" for help.
  spectator:
    description: Server Essentials Command
    usage: 
    permission: server.mod
    permission-message: Unknown command. Type "/help" for help.
  fakeleave:
    description: Server Essentials Command
    usage: 
    permission: server.mod
    permission-message: Unknown command. Type "/help" for help.
  unfakeleave:
    description: Server Essentials Command
    usage: 
    permission: server.mod
    permission-message: Unknown command. Type "/help" for help.
  spawn:
    description: Server Essentials Command
    usage: 
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  shop:
    description: Server Essentials Command
    usage: 
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  trail:
    description: Server Essentials Command
    usage: 
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  dab:
    description: Server Essentials Command
    usage: 
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  shrug:
    description: Server Essentials Command
    usage: 
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  about:
    description: Server Essentials Command
    usage: 
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  mute:
    description: Server Essentials Command
    usage: 
    permission: server.mod
    permission-message: You are not allowed to use this command!
  ban:
    description: Server Essentials Command
    usage: 
    permission: server.mod
    permission-message: You are not allowed to use this command!
  bc:
    description: Server Essentials Command
    usage: 
    permission: server.mod
    permission-message: You are not allowed to use this command!
  broadcast:
    description: Server Essentials Command
    usage: 
    permission: server.mod
    permission-message: You are not allowed to use this command!