main: tld.example.myplugin.Main
name: ServerEssentials
version: 0.0.6
author: KingCloudNinja
description: Server Essentials Plugin
commands:
  spec:
    description: Server Essentials Command
    permission: server.mod
    permission-message: Unknown command. Type "/help" for help.
  spectator:
    description: Server Essentials Command
    permission: server.mod
    permission-message: Unknown command. Type "/help" for help.
  fakeleave:
    description: Server Essentials Command
    permission: server.mod
    permission-message: Unknown command. Type "/help" for help.
  fakejoin:
    description: Server Essentials Command
    permission: server.mod
    permission-message: Unknown command. Type "/help" for help.
  spawn:
    description: Server Essentials Command
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  shop:
    description: Server Essentials Command
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  trail:
    description: Server Essentials Command
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  dab:
    description: Server Essentials Command
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  shrug:
    description: Server Essentials Command
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  about:
    description: Server Essentials Command
    permission: server.all
    permission-message: Unknown command. Type "/help" for help.
  bc:
    description: Server Essentials Command
    permission: server.mod
    permission-message: You are not allowed to use this command!
  broadcast:
    description: Server Essentials Command
    permission: server.mod
    permission-message: You are not allowed to use this command!
  fly:
    description: Server Essentials Command
    permission: server.fly
    permission-message: You are not allowed to use this command!
  eat:
    description: Server Essentials Command
    permission: server.eat
    permission-message: You are not allowed to use this command!
  feed:
    description: Server Essentials Command 
    permission: server.eat
    permission-message: You are not allowed to use this command!
  heal:
    description: Server Essentials Command 
    permission: server.heal
    permission-message: You are not allowed to use this command!
  restore:
    description: Server Essentials Command 
    permission: server.heal
    permission-message: You are not allowed to use this command!
  se:
    description: Server Essentials Command
    permission: server.admin
    permission-message: Unknown command. Type "/help" for help.
  serveressentials:
    description: Server Essentials Command
    permission: server.admin
    permission-message: Unknown command. Type "/help" for help.